### ISSUE TITLE
[Question] Handling of branch change

### ISSUE THREAD

**Issue by chris42** [stefanhh0/aosp-10#4]
Hi there,
just another question. ;-)

How do you handle branch switch? I do remove everything and start over. Not sure if cleaning the git and switching would work and therefore save time? Do you have experience with that? Every time I tried, i got a messy build.

BTW: find attached my version of the script FYI.
[build-10-4.9.sh.txt](https://github.com/stefanhh0/aosp-10/files/4102642/build-10-4.9.sh.txt)

**Comment by stefanhh0** [comment]
Hey @chris42,

sorry for my late reply, I didn't setup an email for notification, just changed that setting.

Yes, indeed branch switch is a problem with the script. I don't have a clear strategy yet, well with February patch there will be the next opportunity to look into it to get it sorted out.

What I do when it happens is pretty manual:
- Move the opengapps away from the src-directory
- Hard reset the changed files .repo/ 
- Switch branch
- repo sync --force-sync
- repo-update.sh
- Manually cleanup here and there
- Move back opengapps into the src-directory
- Start build.sh script

Thanks for sending me your version of the script, I'll have a look into and will try to improve my script somehow.

**Comment by chris42** [comment]
No worries, was not in a hurry, more curious. 

Not sure if it is needed anymore :-(. Sony moved Loire to legacy, hence will only use android 10 with 4.9. Don't know yet how that will impact the updates, but I guess Android 10 will be the last version (if it will be running without errors at all at some time).

My script just has changes in there to use microg instead of opengapps and gives the opportunity to do a quick recompile without cleaning. Also I use it within a docker, to keep the build environment stable and portable. Hence the variables are set in the docker.

**Comment by stefanhh0** [comment]
Yes, I have seen that and I am sorry about it. They don't have the man-power to support it and not only that but there have been also bigger complications than with the other platforms, it was something with the blobs compatibility with k-4.14 and Alin even tried to hexedit some stuff before he gave up and requested the platfoms loire and tone being marked as legacy.

The idea of my scripts here is just too keep them as long alive as I have problems using the default build from sodp, so I am not planning putting too much energy into smooth switching branches. I plan to do a little work on that with the next switch, maybe I find a not too difficult solution for it.

Currently fighting with opengapps, apparently the same issue as you had before... Maybe it is the SetupWizard version could also be that in fact GooglePermissionController is required, since you have reported that behavior on 4th of Januar, that time I only was no longer using the GooglePermissionConntroller no longer.

**Comment by chris42** [comment]
I always hoped, that Sony would get some synergies out of the OSS program, but it seems, that there is quite a divide between the regular development and the AOSP blobs. For me it is troubling, as there is pretty much no other compact phone left to choose from.

I actually never debugged the Issue I had with the permission controller as I was switching to microg either way. There we have a lot of issues with the permissions as well, mostly wrong defined permission lists and whitelists.

BTW: The latest build wasn't working for me either. Marjin seems to have changed something around the thermal commits. Removing them works, but haven't tested the results yet.
Will now wait and see what the whole legacy thing will do.

**Comment by stefanhh0** [comment]
I have figured out what the problem is with opengapps. SetupWizard has in fact a problem, when reverting to an older Version it just works, so I am back to AOSP after using the terrible stock for a day.

If you exclude the thermal hal stuff you may find tombstone files. Besides that it seems to have not too much of having an effect. Is it for throttling when it gets too hot? Not sure, anyway it is winter :-) Marjin wanted to discuss internally what to do with it... thanks for the hint, I will update the commit-hash codes accordingly.

Maybe I am going to try as well microg soon, I am a little to used though using gapps, it is pretty comfortable, though I know that comes with a price...

**Comment by chris42** [comment]
> Maybe I am going to try as well microg soon, I am a little to used though using gapps, it is pretty comfortable, though I know that comes with a price...

Microg is actually quite nice, especially the control you get in location services. But if you use a lot of apps depending on the google framework or safetynet, it is a pain. Marvin didn't have too much time last year to work on microg, so now a lot of apps are broken. For me it works as I only use a few.

Marvin hinted, that he would focus this year on getting apps to work, but can't tell about it's schedule.

**Comment by stefanhh0** [comment]
Hey @chris42,

I've just pushed a new version of the script, that should support branch switching, well I haven't tested it yet but will do so as soon as SODP switches to the February AOSP-Release.

I know your device has been put to legacy so you have to tailor your on script, but maybe some of the functions I have created may help you. I guess it wouldn't need too big adjustments.

Best regards,
Stefan

**Comment by chris42** [comment]
Thanks a lot. Will check it. Need to rework the script either way and incorporate some fixes by ix5.

**Comment by stefanhh0** [comment]
I've tested now successfully the branch switch functionality and it required a fix for sure!
What is not tested does not work, as my good old colleague used to say to me... ;-)

I have also added a --keep-local switch, which may help you staying on the android 10 legacy branch for the local-manifests. Additionally improved some other minor things.

If you have any feedback or suggestions for further improvement please let me know.
