### ISSUE TITLE
[Question] Handling legacy branch

### ISSUE THREAD

**Issue by chris42** [stefanhh0/aosp-10#5]
Hi there,

as you might have seen on the Loire issues at Sony, I am trying to get Kugo running.
I started with adapting the script and figured, that you use the regular local_manifest branch instead of android-10_legacy. Hence your reverts etc. are quite different. Is there a reason for that?

**Comment by stefanhh0** [comment]
Hello Chris, yes, the android-10_legacy is not meant for yoshino/lilac, the device I am mainly interested in. You'd have to adjust it to your needs. It twill be then less to adjust? I don't know if it it is currently good enough to build the legacy devices as well, anyway I guess it makes sense to have a setup with android-10_legacy because that is what is being supported  in the futue.

**Comment by chris42** [comment]
Ok, I understand and I agree. :-) 
My setup will base on the legacy branch. I am running a compile right now - hope it works - then I will add some more stuff. While checking all the changes you made, I stumbled upon the following:

- Why in the local manifests do you switch the media and display HAL to 8.1? Are there any benefits or things that got fixed by that?
- Why do you do the following?
        # treble/vintf: Bump graphics.composer to version 2.3.
        git revert --no-edit 0634f99808583bac9586649da024c1e24d14964b
- I can't find the commit?
        # remove the no-op Android.bp
        git revert --no-edit fd3e6c8c993d3aa7ef7ae9856d37dc09d4bbcf3f
- I can't find the commit either
        # PowerHAL: power-helper: Fix WLAN STATS file path for k4.14
        git revert --no-edit d3cbedf701aa8ab1ed7d571b5fb384665c92df03
- This seems to be different commit as well, looking at #470 (Thermal tombstone)?
        git fetch https://github.com/MarijnS95/device-sony-common
        # common-packages: Include default thermal hw module.
        git cherry-pick --no-edit bccbb5d57ea6605f7f814e547e46c32257c4b193

Just curious, what your thought were about it.

**Comment by chris42** [comment]
So figured most of the things above. ;-) And as Sony is just updating the legacy branch, a lot of stuff moves into the regular repositories and won't need reverts anymore. Will see what comes out of that.

**Comment by stefanhh0** [comment]
Hey @chris42,

find my answers inline, even if you already figured it out yourself :-)

>     * Why in the local manifests do you switch the media and display HAL to 8.1? Are there any benefits or things that got fixed by that?

I just revert the commit and stick to the old 7.3 the ones that are also used for Android 9 alongside with k4.9. A comment like: `# qcom: Switch SM8150 media HAL to LA.UM.8.1.r1 codebase` is just the commit headline of the commit that is being then reverted in the next line of the script. The reverts are done because those commits are meant for k4.14 and are not compatible with k4.9.

>     * Why do you do the following?
>       # treble/vintf: Bump graphics.composer to version 2.3.
>       git revert --no-edit 0634f99808583bac9586649da024c1e24d14964b

Same as above, 2.3 does not work with k4.9 resp. legacy qcom display branches. 

>     * I can't find the commit?
>       # remove the no-op Android.bp
>       git revert --no-edit fd3e6c8c993d3aa7ef7ae9856d37dc09d4bbcf3f

That is unexpected:
```
stefan@mars:~/android/source/device/sony/common$ git log fd3e6c8c993d3aa7ef7ae9856d37dc09d4bbcf3f
commit fd3e6c8c993d3aa7ef7ae9856d37dc09d4bbcf3f
Author: Alin Jerpelea <alin.jerpelea@sony.com>
Date:   Thu Sep 26 09:27:40 2019 +0200

    remove the no-op Android.bp
    
    The no-op fix is not needed for Android 10
    
    Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>
```

>     * I can't find the commit either
>       # PowerHAL: power-helper: Fix WLAN STATS file path for k4.14
>       git revert --no-edit d3cbedf701aa8ab1ed7d571b5fb384665c92df03

As above, you should be able to find it. Are you having a shallow clone sitting in device/sony/common?

>     * This seems to be different commit as well, looking at #470 (Thermal tombstone)?
>       git fetch https://github.com/MarijnS95/device-sony-common
>       # common-packages: Include default thermal hw module.
>       git cherry-pick --no-edit bccbb5d57ea6605f7f814e547e46c32257c4b193

Yes, that is something I have just fixed.

Best regards
Stefan

**Comment by chris42** [comment]
Regarding the missing commits, I always searched on github. Maybe it is similar as with Marjins commits. Don't know.
With the updated repo, at least the reverts are not necessary for me anymore. Only custom things I use now are the the WLAN PR and the thermal stuff.

**Comment by stefanhh0** [comment]
Okay, yes github search seems to be not too reliable. Between HEAD and the commits in question are many hundred commits because of some ims stuff that was integrated by Alin some time ago. However if you use git from command-line it should just show the commit. It is a different situation than with the commits from Marijn repository, since the history of the master branch of the main device-sony-common repository has not been rewritten.

Good to hear that you are making progress with getting the legacy branch running.
